#define PI 3.14159265
#define FLOAT_MAX 3.4028235e+38
#define FLOAT_MIN -FLOAT_MAX
#define FLOAT_NAN (0.0 / 0.0)

#define ENUM_ANTI_ALIASING_MODE uint
#define ENUM_ANTI_ALIASING_MODE_NONE 0
#define ENUM_ANTI_ALIASING_MODE_TAA 1
#define ENUM_ANTI_ALIASING_MODE_FSR 2

#define ENUM_SHADOW_MODE uint
#define ENUM_SHADOW_MODE_NONE 0
#define ENUM_SHADOW_MODE_PCF 1
#define ENUM_SHADOW_MODE_RAY_TRACED 2

#define MESHLET_MAX_VERTEX_COUNT 128
#define MESHLET_MAX_TRIANGLE_COUNT 252
