#define TILE_SIZE 16

#define ENUM_SHADING_RATE uint
#define ENUM_SHADING_RATE_1_INVOCATION_PER_PIXEL_NV 0u
#define ENUM_SHADING_RATE_1_INVOCATION_PER_2X1_PIXELS_NV 1u
#define ENUM_SHADING_RATE_1_INVOCATION_PER_2X2_PIXELS_NV 2u
#define ENUM_SHADING_RATE_1_INVOCATION_PER_4X2_PIXELS_NV 3u
#define ENUM_SHADING_RATE_1_INVOCATION_PER_4X4_PIXELS_NV 4u

// Keep in sync between shader and client code!
#define ENUM_DEBUG_MODE uint
#define ENUM_DEBUG_MODE_SHADING_RATES      1u
#define ENUM_DEBUG_MODE_SPEED              2u
#define ENUM_DEBUG_MODE_LUMINANCE          3u
#define ENUM_DEBUG_MODE_LUMINANCE_VARIANCE 4u